name: Build and Deploy WAR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 14
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build WAR
        run: jar cvf helloworld.war WEB-INF

      - name: Display WAR file
        run: ls helloworld.war

      - name: Deploy WAR
        run: |
          mkdir -p deployment
          cp helloworld.war deployment/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: helloworld.war
          asset_name: helloworld.war
          tag: ${{ github.ref }}
          overwrite: true
          body: "HAve fun :)"
